services:
  livemotion:
    image: ghcr.io/dttxorg/livemotion:0.1.0
    container_name: livemotion
    restart: unless-stopped
    environment:
      CONFIG_PATH: /config/config.json
      DB_PATH: /config/livephoto-worker.sqlite3
      LOG_LEVEL: INFO
      WEB_PORT: "8011"
    ports:
      - "8011:8011"
    volumes:
      - /vol2/photos:/photos
      - /vol1/docker/livephoto-worker/config:/config
